// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace NorthWeird.WebApiTests
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Categories.
    /// </summary>
    public static partial class CategoriesExtensions
    {
            /// <summary>
            /// Retrieves a category list
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GET(this ICategories operations)
            {
                operations.GETAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves a category list
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GETAsync(this ICategories operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.GETWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
