// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace NorthWeird.WebApiTests
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for NorthWeirdAPI.
    /// </summary>
    public static partial class NorthWeirdAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void Get(this INorthWeirdAPI operations)
            {
                operations.GetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GetAsync(this INorthWeirdAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.GetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Retrieves a product list that contains full list of products
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void Get1(this INorthWeirdAPI operations)
            {
                operations.Get1Async().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves a product list that contains full list of products
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task Get1Async(this INorthWeirdAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.Get1WithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Creates product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='product'>
            /// Product that needs to be created
            /// </param>
            public static void Post(this INorthWeirdAPI operations, ProductDto product = default(ProductDto))
            {
                operations.PostAsync(product).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='product'>
            /// Product that needs to be created
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostAsync(this INorthWeirdAPI operations, ProductDto product = default(ProductDto), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostWithHttpMessagesAsync(product, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Retrieves a specific product by unique id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Id of the product
            /// </param>
            public static void ProductGet(this INorthWeirdAPI operations, int id)
            {
                operations.ProductGetAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves a specific product by unique id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Id of the product
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ProductGetAsync(this INorthWeirdAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ProductGetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Updates product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// id of the product that needs to be updated
            /// </param>
            /// <param name='product'>
            /// Product that needs to be updated
            /// </param>
            public static void Put(this INorthWeirdAPI operations, int id, ProductDto product = default(ProductDto))
            {
                operations.PutAsync(id, product).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Updates product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// id of the product that needs to be updated
            /// </param>
            /// <param name='product'>
            /// Product that needs to be updated
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PutAsync(this INorthWeirdAPI operations, int id, ProductDto product = default(ProductDto), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PutWithHttpMessagesAsync(id, product, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Deletes product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// id of the product that needs to be deleted
            /// </param>
            public static void Delete(this INorthWeirdAPI operations, int id)
            {
                operations.DeleteAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes product from request body
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// id of the product that needs to be deleted
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAsync(this INorthWeirdAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
